/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
// import {useFrame,useThree} from '@react-three/fiber'
import RoomScene from '../3d/final_Room.glb'
import {a} from '@react-spring/three'

const Room = (props)=> {
  const roomRef = useRef();
  const { nodes, materials } = useGLTF(RoomScene)
  return (
    <a.group ref ={roomRef} {...props} >
      <group scale={1.096}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.chair_form.geometry}
          material={materials['gaming_chair_progress_uvblinn6.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.chair_form_1.geometry}
          material={materials['blinn1.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.chair_form_2.geometry}
          material={materials['gaming_chair_progress_uvblinn4.001']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.leftTableFoot.geometry}
        material={materials.Black}
        scale={1.096}
      />
      <group scale={1.096}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube005.geometry}
          material={materials.Black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube005_1.geometry}
          material={materials.sidePannel}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.rightTableFoot.geometry}
        material={materials.Black}
        scale={1.096}
      />
      <group scale={1.096}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube006.geometry}
          material={materials.Black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube006_1.geometry}
          material={materials.Material}
        />
      </group>
      <group scale={1.096}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube004.geometry}
          material={materials.Black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube004_1.geometry}
          material={materials['Material.001']}
        />
      </group>
      <group scale={1.096}>
        <mesh castShadow receiveShadow geometry={nodes.Plane.geometry} material={materials.frame} />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane_1.geometry}
          material={materials['Material.007']}
        />
      </group>
      <group scale={1.096}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane001.geometry}
          material={materials.frame}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane001_1.geometry}
          material={materials['Material.006']}
        />
      </group>
      <group scale={1.096}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane002.geometry}
          material={materials.frame}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane002_1.geometry}
          material={materials['Material.003']}
        />
      </group>
      <group scale={1.096}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube.geometry}
          material={materials.Monitor_Frame}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_1.geometry}
          material={materials['Material.002']}
        />
      </group>
      <group scale={1.096}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane003.geometry}
          material={materials.Black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane003_1.geometry}
          material={materials['Material.012']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.keyBoard.geometry}
        material={materials.Monitor_Frame}
        scale={1.096}
      />
      <group scale={1.096}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube010.geometry}
          material={materials.Monitor_Frame}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube010_1.geometry}
          material={materials.monitorScreen}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube010_2.geometry}
          material={materials['Material.004']}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.monitorStand.geometry}
        material={materials.Monitor_Frame}
        scale={1.096}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wire.geometry}
        material={materials['Material.013']}
        scale={1.096}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.leftHandle.geometry}
        material={materials['Material.009']}
        scale={1.096}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.rightHandle.geometry}
        material={materials.Black}
        scale={1.096}
      />
      <group scale={1.096}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube003.geometry}
          material={materials['Material.008']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube003_1.geometry}
          material={materials.floor}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube003_2.geometry}
          material={materials.GLASS}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube003_3.geometry}
          material={materials.windowFrame}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube003_4.geometry}
          material={materials.windowFrame}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube003_5.geometry}
          material={materials['sky Wall']}
        />
      </group>
      <mesh
        name="Teeth"
        castShadow
        receiveShadow
        geometry={nodes.Teeth.geometry}
        material={materials.Teeth}
        morphTargetDictionary={nodes.Teeth.morphTargetDictionary}
        morphTargetInfluences={nodes.Teeth.morphTargetInfluences}
        position={[0.844, 1.351, 4.128]}
        rotation={[0, 1.219, 0]}
        scale={0.259}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Shoes.geometry}
        material={materials.Shoes}
        position={[0.844, 1.351, 4.128]}
        rotation={[0, 1.219, 0]}
        scale={0.259}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Shirt.geometry}
        material={materials.Shirt}
        position={[0.844, 1.351, 4.128]}
        rotation={[0, 1.219, 0]}
        scale={0.259}
      />
      <mesh
        name="RightEye"
        castShadow
        receiveShadow
        geometry={nodes.RightEye.geometry}
        material={materials.LeftEye}
        morphTargetDictionary={nodes.RightEye.morphTargetDictionary}
        morphTargetInfluences={nodes.RightEye.morphTargetInfluences}
        position={[0.844, 1.351, 4.128]}
        rotation={[0, 1.219, 0]}
        scale={0.259}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Pants.geometry}
        material={materials.Pants}
        position={[0.844, 1.351, 4.128]}
        rotation={[0, 1.219, 0]}
        scale={0.259}
      />
      <group position={[0.844, 1.351, 4.128]} rotation={[0, 1.219, 0]} scale={0.259}>
        <mesh
          name="MainHead_1"
          castShadow
          receiveShadow
          geometry={nodes.MainHead_1.geometry}
          material={materials['skin.002']}
          morphTargetDictionary={nodes.MainHead_1.morphTargetDictionary}
          morphTargetInfluences={nodes.MainHead_1.morphTargetInfluences}
        />
        <mesh
          name="MainHead_2"
          castShadow
          receiveShadow
          geometry={nodes.MainHead_2.geometry}
          material={materials['teeth.002']}
          morphTargetDictionary={nodes.MainHead_2.morphTargetDictionary}
          morphTargetInfluences={nodes.MainHead_2.morphTargetInfluences}
        />
      </group>
      <mesh
        name="LeftEye"
        castShadow
        receiveShadow
        geometry={nodes.LeftEye.geometry}
        material={materials.LeftEye}
        morphTargetDictionary={nodes.LeftEye.morphTargetDictionary}
        morphTargetInfluences={nodes.LeftEye.morphTargetInfluences}
        position={[0.844, 1.351, 4.128]}
        rotation={[0, 1.219, 0]}
        scale={0.259}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.hands.geometry}
        material={materials.hands}
        position={[0.844, 1.351, 4.128]}
        rotation={[0, 1.219, 0]}
        scale={0.259}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.hair.geometry}
        material={materials.Hair}
        position={[0.844, 1.351, 4.128]}
        rotation={[0, 1.219, 0]}
        scale={0.259}
      />
      <mesh
        name="EyeBrow"
        castShadow
        receiveShadow
        geometry={nodes.EyeBrow.geometry}
        material={materials.Hair}
        morphTargetDictionary={nodes.EyeBrow.morphTargetDictionary}
        morphTargetInfluences={nodes.EyeBrow.morphTargetInfluences}
        position={[0.844, 1.351, 4.128]}
        rotation={[0, 1.219, 0]}
        scale={0.259}
      />
    </a.group>
  )
}


export default Room;